package com.bright.wallet.dto;

/**
 * PaystackInitiateResponseDto
 *
 * Returned by POST /payments/deposit/initiate.
 * The frontend uses authorizationUrl to redirect the user to Paystack checkout.
 * The reference is stored for later verification via GET /payments/verify.
 */
public class PaystackInitiateResponseDto {

    /** Paystack-hosted payment page URL — redirect the user here. */
    private String authorizationUrl;

    /**
     * Unique transaction reference generated by Paystack.
     * Store this in the browser (e.g. sessionStorage) so it survives the redirect.
     */
    private String reference;

    public PaystackInitiateResponseDto() {}

    public PaystackInitiateResponseDto(String authorizationUrl, String reference) {
        this.authorizationUrl = authorizationUrl;
        this.reference        = reference;
    }

    public String getAuthorizationUrl() { return authorizationUrl; }
    public String getReference()        { return reference; }
}